#!/usr/bin/env python3

import sys
sys.path.append("python")
sys.path.append("/var/tmp")

import MyGame.Example.Monster
import MyGame.Example.Test

with open('tests/monsterdata_test.mon', 'rb') as f:
  monster = MyGame.Example.Monster.Monster.GetRootAs(f.read())
  print(monster.Pos())
  print(monster.Pos().X())
  print(monster.Pos().Y())
  print(monster.Pos().Z())
  print(monster.Pos().Test1())
  print(monster.Pos().Test2())
  test = MyGame.Example.Test.Test()
  print(monster.Pos().Test3(test))
  print(monster.Pos().Test3(test).A())
  print(monster.Pos().Test3(test).B())
  print(monster.Hp())
  print(monster.Mana())
  print(monster.Name())
  print(monster.Color())
  print(monster.InventoryLength())
  print(monster.Inventory(0))
  print(monster.TestarrayoftablesLength())
  print(monster.TestarrayofstringLength())
  print(monster.Testarrayofstring(0))
  print(monster.Testarrayofstring2Length())
  print(monster.TestarrayofboolsLength())
  print(monster.Testarrayofbools(0))
  print(monster.TestarrayofsortedstructLength())
  print(monster.Testarrayofsortedstruct(0).Distance())
  print(monster.Testarrayofsortedstruct(1).Distance())
  print(monster.Testarrayofsortedstruct(2).Distance())
  print(monster.Enemy())
  print(monster.TestType())
  print(monster.Test())
  test = MyGame.Example.Monster.Monster()
  test.Init(monster.Test().Bytes, monster.Test().Pos)
  print(test.Name())
  print(monster.Test4(0).A())
  print(monster.Test4(0).B())
  print(monster.Test4(1).A())
  print(monster.Test4(1).B())
  print(monster.Test5(0).A())
  print(monster.Test5(0).B())
  print(monster.Test5(1).A())
  print(monster.Test5(1).B())
  print(monster.Testnestedflatbuffer(0))
  print(monster.Testhashs32Fnv1())
  print(monster.Testhashu32Fnv1())
  print(monster.Testhashs64Fnv1())
  print(monster.Testhashu64Fnv1())
  print(monster.Testhashs32Fnv1a())
  print(monster.Testhashu32Fnv1a())
  print(monster.Testhashs64Fnv1a())
  print(monster.Testhashu64Fnv1a())
  print(monster.Testf())
  print(monster.Testf2())
  print(monster.Testf3())
  print(monster.FlexLength())
  print(monster.VectorOfLongsLength())
  print(monster.VectorOfLongs(0))
  print(monster.VectorOfLongs(4))
  print(monster.VectorOfDoublesLength())
  print(monster.VectorOfDoubles(0))
  print(monster.VectorOfDoubles(2))
  print(monster.ParentNamespaceTest())
  print(monster.VectorOfReferrablesLength())
  print(monster.SingleWeakReference())
  print(monster.VectorOfWeakReferencesLength())
  print(monster.VectorOfStrongReferrablesLength())
  print(monster.CoOwningReference())
  print(monster.VectorOfCoOwningReferencesLength())
  print(monster.NonOwningReference())
  print(monster.VectorOfNonOwningReferencesLength())
  print(monster.AnyUnique())
  print(monster.AnyAmbiguous())
  print(monster.VectorOfEnumsLength())
  print(monster.SignedEnum())
  print(monster.TestrequirednestedflatbufferLength())
  print(monster.ScalarKeySortedTablesLength())
  print(monster.ScalarKeySortedTables(0))
  print(monster.ScalarKeySortedTables(1))
  print(monster.NativeInline().A())
  print(monster.NativeInline().B())
  print(monster.LongEnumNonEnumDefault())
  print(monster.LongEnumNormalDefault())
  print(monster.NanDefault())
  print(monster.InfDefault())
  print(monster.PositiveInfDefault())
  print(monster.InfinityDefault())
  print(monster.PositiveInfinityDefault())
  print(monster.NegativeInfDefault())
  print(monster.NegativeInfinityDefault())
  print(monster.DoubleInfDefault())
